app = "autonomous-scraper"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 8501
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[mounts]
  source = "app_data"
  destination = "/persist"
