name: Scrape → Summarize → Publish (12h)

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug repo structure
        run: |
          pwd
          ls -R

      - name: Scrape
        env:
          EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
        run: |
          python stratfor_india_agent.py
          mkdir -p data
          cp stratfor_feed_india.json data/latest_raw.json || echo "No raw file found."

      - name: Summarize
        run: |
          python summarization_stratfor.py
          mkdir -p data
          cp stratfor_feed_india_extractive.json data/latest_summary.json || echo "No summary file found."

      - name: Commit data changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest_raw.json data/latest_summary.json 2>/dev/null || true
          git diff --cached --quiet || git commit -m "auto: update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push || true
